name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          cache: 'pnpm'
      - name: Install dependencies
        run: |
          if ! pnpm install --frozen-lockfile; then
            echo "Lock file is outdated, updating..."
            pnpm install
            git diff
            exit 1
          fi
      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
